### ISSUE TITLE
Extra zero padding on collectd packets

### ISSUE THREAD

**Issue by jhenry82** [astro/node-collectdout#10]
I recently deployed the CollectM project (https://github.com/perfwatcher/collectm), which embeds your library, on our Windows servers. I found that after a period of time ranging from minutes to hours, the remote collectd server being written to would start consuming all available memory before finally being nuked by the OOM killer. Which is obviously a horrible bug on the main collectd project's part, but I wanted to see what was different about the traffic coming from node-collectdout to trigger it.

The remote server is currently running collectd 5.4.2 and has been handling about 600 Linux clients with no issue for years. As soon as we added the Windows client (using node-collectdout), the problem surfaced. I disabled the 15 or so Windows clients, and it immediately stabilized. 

I captured the traffic between the collectd server and a Windows client, and Wireshark's collectd parser flagged every packet as invalid. Due to a bunch of 0x00 bytes at the end. Looking at the code, it sends a 1024 byte payload every time, regardless of the actual length of the data. A bunch of zeroes are sent after the end of the data to fill out the packet.

I modified the code to match the packet size to the data. Since deploying that patch, the server has been running with zero issues. I'll submit a pull request shortly. nodejs is definitely not my "native language" so I'm open to suggestions on how to do this differently.

Even if collectd fixes their server to handle this better, it's still preferable not to send hundreds of bytes of pointless zeroes. Not a big deal in the era of 10 gig ethernet, but still :)

**Comment by astro** [comment]
Cc: @octo

**Comment by feraudet** [comment]
Cc @ymettier

**Comment by jhenry82** [comment]
Thanks for the quick merge! If you are happy with the fix, any chance you could cut a new 0.0.9 (or whatever) release, so consumers of the lib can easily update?

**Comment by astro** [comment]
0.0.9 released. Sorry for the delay.
